### PR TITLE
releases 0.2.1: support async-std and tokio as runtime

### PR DESCRIPTION
**Pull request by macrocan**

### CODE REVIEW

**Comment by dvc94ch** [comment]
Would it be possible to use async-global-executor/async-io instead of async-std? I think those are the only parts of async-std that are really needed

**Comment by kingwel-xie** [comment]
> Would it be possible to use async-global-executor/async-io instead of async-std? I think those are the only parts of async-std that are really needed

Sure, we can do that as you pointed out. But we thought there is possibilities we need more in future. f.g., replace futures::sync::mutext with async-mutex? So, to keep it simple, we refer to the entire async-std at this moment.

What's your concern? Bigger footprint of the bin file?

**Comment by dvc94ch** [comment]
well the original idea was that code only using async-io could be considered executor independent (the tokio people disagree). I like the clear executor/reactor split, and I think that the api surface and size of async-io is sufficiently small that it become part of std some day. things like mutexes/channels use an `AtomicWaker` in the background and are completely independent of executors/reactors/oses so they aren't really a concern when writing code that needs to work on multiple executors.

**Comment by kingwel-xie** [comment]
> well the original idea was that code only using async-io could be considered executor independent (the tokio people disagree). I like the clear executor/reactor split, and I think that the api surface and size of async-io is sufficiently small that it become part of std some day. things like mutexes/channels use an `AtomicWaker` in the background and are completely independent of executors/reactors/oses so they aren't really a concern when writing code that needs to work on multiple executors.

Good point. Will give it a try someday. Thanks!

**Pull request merged**
